### PR TITLE
flush data still available in the decoder when no input (#123)

### LINKED ISSUE #123: Decoder might block if there is data remaining to be flushed from the codec and the stream blocks
See https://github.com/gyscos/zstd-rs/issues/119, I'm pretty sure the local `bufread::Decoder` implementations suffer from this same issue. My first attempt at writing a test case failed to fail though.

### PR DESCRIPTION
**Pull request by robjtede**
rebased #129 

closes #123

### CODE REVIEW

**Comment by michalfita** [comment]
Pinging @NobodyXu may speed up things.
Thank you for doing this @robjtede.

**Review by NobodyXu — CHANGES_REQUESTED** [review]

**Comment by NobodyXu** [comment]
Sorry, I reviewed this afternoon but forgot to publish it.

File: src/codec/gzip/decoder.rs [hunk 1]
```diff
@@ -80,8 +80,20 @@ impl GzipDecoder {
...
+                        // from the decoder, to update the crc
+                        err if err.kind() == std::io::ErrorKind::Other
+                            && !output.written().is_empty() =>
+                        {
+                            Ok(false)
+                        }
+                        _ => Err(err),
+                    })?;
+
                     self.crc.update(&output.written()[prior..]);
```
Comment (NobodyXu) [inline src/codec/gzip/decoder.rs:95]: How about changing it to this to avoid swallowing error:

```suggestion
                    let res = inner(self, input, output);

                    if (output.written().len() > prior) {
                        self.crc.update(&output.written()[prior..]);
                    }
                    
                    let done = res?;
```

**Review by NobodyXu — CHANGES_REQUESTED** [review]

**Comment by NobodyXu** [comment]
cc @robjtede

**Comment by robjtede** [comment]
sorry for the (mega) delay, hope this can get into the release

**Review by NobodyXu — APPROVED** [review]
Thanks, LGTM
